### ISSUE TITLE
Nicer configuration of repositories as services

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Doctrine#216]
```yml
doctrine:
    repositories:
        App\Blog\Article: App\Blog\ArticleRepository()
```
