### ISSUE TITLE
Use default Doctrine in OrmExtension

### ISSUE THREAD

**Issue by foxycode** [Kdyby/Doctrine#241]
Connection setting is under `doctrine / dbal / connections` DoctrineBundle: http://symfony.com/doc/current/reference/configuration/doctrine.html

I'd like it same way to not think what is different in `Kdyby\Doctrine` against default implementation.

I currently using config like this:
```php
doctrine:
    metadata:
        App\Model\Entities: %appDir%/model/Entities
    types:
        convertabledatetime: App\Model\ConvertableDateTimeType
    dql:
        datetime:
            date:           Oro\ORM\Query\AST\Functions\SimpleFunction
            time:           Oro\ORM\Query\AST\Functions\SimpleFunction
            timestamp:      Oro\ORM\Query\AST\Functions\SimpleFunction
            convert_tz:     Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
            timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
            dayofyear:      Oro\ORM\Query\AST\Functions\SimpleFunction
            dayofmonth:     Oro\ORM\Query\AST\Functions\SimpleFunction
            dayofweek:      Oro\ORM\Query\AST\Functions\SimpleFunction
            week:           Oro\ORM\Query\AST\Functions\SimpleFunction
            day:            Oro\ORM\Query\AST\Functions\SimpleFunction
            hour:           Oro\ORM\Query\AST\Functions\SimpleFunction
            minute:         Oro\ORM\Query\AST\Functions\SimpleFunction
            month:          Oro\ORM\Query\AST\Functions\SimpleFunction
            quarter:        Oro\ORM\Query\AST\Functions\SimpleFunction
            second:         Oro\ORM\Query\AST\Functions\SimpleFunction
            year:           Oro\ORM\Query\AST\Functions\SimpleFunction
        numeric:
            sign:           Oro\ORM\Query\AST\Functions\Numeric\Sign
            pow:            Oro\ORM\Query\AST\Functions\Numeric\Pow
        string:
            group_concat:   Oro\ORM\Query\AST\Functions\String\GroupConcat
            concat_ws:      Oro\ORM\Query\AST\Functions\String\ConcatWs
            cast:           Oro\ORM\Query\AST\Functions\Cast
    default:
        driver: pdo_mysql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
    deals:
        driver: pdo_pgsql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
```

I have it splitted to more neon files of course, but still it is weird to have connection names on same level that another config sections. It then creates another problems like this: https://github.com/mrtnzlml/testbench/pull/14

**Comment by fprochazka** [comment]
That is not "default implementation", but symfony's custom config structure. I wouldn't wanna break the compatibility just to be compliant with symfony.

Your configuration can be rewritten to this

```yml
doctrine:
    default:
        driver: pdo_mysql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
        metadata:
            App\Model\Entities: %appDir%/model/Entities
    deals:
        driver: pdo_pgsql
        host: localhost
        user: xxx
        password: xxx
        dbname: xxx
        metadata:
            App\Model\Entities: %appDir%/model/Entities
    types:
        convertabledatetime: App\Model\ConvertableDateTimeType
    dql:
        datetime:
            date:           Oro\ORM\Query\AST\Functions\SimpleFunction
            time:           Oro\ORM\Query\AST\Functions\SimpleFunction
            timestamp:      Oro\ORM\Query\AST\Functions\SimpleFunction
            convert_tz:     Oro\ORM\Query\AST\Functions\DateTime\ConvertTz
            timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
            dayofyear:      Oro\ORM\Query\AST\Functions\SimpleFunction
            dayofmonth:     Oro\ORM\Query\AST\Functions\SimpleFunction
            dayofweek:      Oro\ORM\Query\AST\Functions\SimpleFunction
            week:           Oro\ORM\Query\AST\Functions\SimpleFunction
            day:            Oro\ORM\Query\AST\Functions\SimpleFunction
            hour:           Oro\ORM\Query\AST\Functions\SimpleFunction
            minute:         Oro\ORM\Query\AST\Functions\SimpleFunction
            month:          Oro\ORM\Query\AST\Functions\SimpleFunction
            quarter:        Oro\ORM\Query\AST\Functions\SimpleFunction
            second:         Oro\ORM\Query\AST\Functions\SimpleFunction
            year:           Oro\ORM\Query\AST\Functions\SimpleFunction
        numeric:
            sign:           Oro\ORM\Query\AST\Functions\Numeric\Sign
            pow:            Oro\ORM\Query\AST\Functions\Numeric\Pow
        string:
            group_concat:   Oro\ORM\Query\AST\Functions\String\GroupConcat
            concat_ws:      Oro\ORM\Query\AST\Functions\String\ConcatWs
            cast:           Oro\ORM\Query\AST\Functions\Cast
```

basically everything should be possible to add only to the section of the named configuration (under `default` or `deals`).
