### ISSUE TITLE
Wrap tools listeners ResolveTargetEntityListener and DebugUnitOfWorkListener and add to config

### ISSUE THREAD

**Issue by mishak87** [Kdyby/Doctrine#40]
Wrap both listeners with necessary code to make them work with Kdyby/Events.
## ResolveTargetEntityListener

``` yaml
rtel:
   <class|interface>: <class> # simple
   <class|interface>: # extended with mapping
      class: <class>
      mapping:
         a: b
```

It might be useful to have extension interface for RTEL.
## DebugUnitOfWorkListener

Probably would be best to have enable option for each event (performance)
Attach to debug panel?
